version: '3.8'

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
  app:
    build: .
    env_file:
      - .env
    volumes:
      - app_data:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
  redis:
    image: redis
    ports:
      - 6379:6379
volumes:
  db_data:
  app_data:
