import os

DB_USERNAME = os.getenv('DB_USERNAME')
DB_PASSWORD = os.getenv('DB_PASSWORD')
DB_DATABASE = os.getenv('DB_DATABASE')
DB_HOSTNAME = os.getenv('DB_HOSTNAME')
DB_PORT = os.getenv('DB_PORT')
SECRET_KEY = os.getenv('SECRET_KEY')
FLASK_DEBUG = os.getenv('FLASK_DEBUG', False)
CACHE_TYPE = os.getenv('CACHE_TYPE')
CACHE_REDIS_HOST = os.getenv('CACHE_REDIS_HOST')
CACHE_REDIS_PORT = os.getenv('CACHE_REDIS_PORT')
CACHE_KEY_PREFIX = os.getenv('CACHE_KEY_PREFIX')


class Config:
    DEBUG = FLASK_DEBUG

    SQLALCHEMY_DATABASE_URI = f'postgresql+psycopg2://{DB_USERNAME}:{DB_PASSWORD}@{DB_HOSTNAME}:{DB_PORT}/{DB_DATABASE}'
    SQLALCHEMY_TRACK_MODIFICATIONS = False

    SECRET_KEY = SECRET_KEY

    CACHE_TYPE = CACHE_TYPE
    CACHE_DEFAULT_TIMEOUT = 10 * 60

    CACHE_REDIS_HOST = CACHE_REDIS_HOST
    CACHE_REDIS_PORT = CACHE_REDIS_PORT
    CACHE_REDIS_URL = f'redis://{CACHE_REDIS_HOST}:{CACHE_REDIS_PORT}'
    CACHE_KEY_PREFIX = CACHE_KEY_PREFIX
